
CC=gcc

all: main

main: util/io.c util/matrix.c data/input.c data/avg.c data/evec.c data/eval.c main.c
	$(CC) util/io.c util/matrix.c data/input.c data/avg.c data/evec.c data/eval.c main.c -o build/main -lm
